### ISSUE TITLE
Can you make a --total hours switch?

### ISSUE THREAD

**Issue by Lukkian** [tomfa/git-csv-timesheet#23]
Thank you for this tool, git-hours keeps giving me install errors.

Could you please consider making a --total hours switch?

In my case I just wanna know how many hours I have spent in my repository.
The problem is is that my repository has 694 commits, feew...

What I would be really glad is something like:
$ timesheet --total
200 hours

**Comment by tomfa** [comment]
Hi @Lukkian - glad it gives you some value.

You can get this stat by using the `--verbose` flag (or `-v` for short):

```
> timesheet --verbose --since=2020-01-01 -i

0 minutes diff until 2020-07-29 20:25 – session starts.
1834 minutes diff until 2020-07-31 07:38 – session starts.
408 minutes diff until 2020-07-31 22:32 – session starts.
484 minutes diff until 2020-08-01 06:36 – session starts.

 Tomas Fagerbekk (tomas.a.fagerbekk@gmail.com) had
 4 sessions constructed using
 67 commits, made in
 1 repositories, done on
 4 different days.

author;date;hours
tomas.a.fagerbekk@gmail.com;2020-07-29;4.4
tomas.a.fagerbekk@gmail.com;2020-07-30;1.2
tomas.a.fagerbekk@gmail.com;2020-07-31;10.1
tomas.a.fagerbekk@gmail.com;2020-08-01;10.8
tomas@webutvikling.org;2020-07-30;1.0

Total hours: 27.6
```

**Comment by Lukkian** [comment]
Cool, thank you.
